### ISSUE TITLE
Multiple "blocks"

### ISSUE THREAD

**Issue by maan75** [eouia/MMM-CountEvents#1]
I'm not sure if it is cool to request an enhancement, but here goes anyway; I absolutely love this module, but it would be even more perfect if it were possible to have different "blocks" of counters or "info-groups" to be displayed in a carousel. This would conserve space in a crowded mirror, but show even more interesting information.

For instance having different counters showing different peoples preferred info: 

1. Block with #days to my birthday, #days until familys birthdays, #days until valentines  etc 
2. Block with #days to GF's birthday, #days until GF's familys birthdays, #days until christmas etc
3. Block with #days until vacation, #days until/since wedding, #days until B&B-day etc
and so on..

I imagine one config file for each "block", and having each config name (with optional timing?!) etc in main config..

**Comment by eouia** [comment]
Nice idea. Let me think how can do this.

**Comment by enzym2004** [comment]
Great idea! It will make this module even better! =)

**Comment by eouia** [comment]
I've made some simple modification. But no transition effect is available due to the structure of this module. (I hadn't considered this feature at development time) So it will change the content without any screen transition effect(fading or anything...). I'm hesitating to release this or not, because not funny. :(

**Comment by maan75** [comment]
Did you consider optional timing? If so, maybe an empty "block" displayed 2-500ms is enough for "transitional effect"?
Either way, I believe having this kind of possibility is more important than transition effects.

**Comment by eouia** [comment]
I've updated. Please test it.

**Comment by maan75** [comment]
Wohoo! You're the man!  Just how i imagined it. :-)
It works like a charm!
:+1: 
:100: :1st_place_medal:

**Comment by eouia** [comment]
I’ll close this issue. Thanks.
