### ISSUE TITLE
Config feature request - display when within x days

### ISSUE THREAD

**Issue by AndyHazz** [eouia/MMM-CountEvents#2]
Great module, but one thing I'd like, literally for Christmas, is the ability to only display a countdown when the targetTime is within X days. 

e.g. something like:

targetTime: "25 Dec 2019",
displayWithin: "25 days"
yearlyRepeat: true,
ignore: "after"

I could then load up the config with lots of yearly events, birthdays etc without having them displayed all year (or constantly editing the config file), only showing up around the time the kids start asking :)

**Comment by eouia** [comment]
Nice idea, I'll consider this on next updates But not guarantee to do soon, sorry.

**Comment by eouia** [comment]
I've modified `ignore` feature to set a valid period for displaying.

- **`ignore: null`** : Always display event
- **`ignore: "before"`** : Hide event before `targetTime`
- **`ignore: "after"`** : Hide event after `targetTime`
- **`ignore: [7, 1]`** : Hide event before 7 days and after 1 days from `targetTime`
- **`ignore: [3, null]`** : Hide event before 3 days from `targetTime`
- **`ignore: [null, 5]`** : Hide event after 5 days from `targetTime` 


Try to test.

**Comment by AndyHazz** [comment]
Sounds perfect. Thanks!
I've been testing and the hide before option works fine, but hide after doesn't seem to? 

```
ignore: [7, 7]
ignore: [7, 364]
ignore: [7, 0]
ignore: [7, null]
```

These all give me the same result, no display after the date.

**Comment by eouia** [comment]
Hmmm it wors for me. 
![image](https://user-images.githubusercontent.com/1720610/74640832-80f5c980-5170-11ea-9cb0-c153839be372.png)

and it shows like this.
![image](https://user-images.githubusercontent.com/1720610/74640860-90751280-5170-11ea-978f-a09603297699.png)

**Comment by AndyHazz** [comment]
I can't check until later today, but I'm using `yearlyRepeat: true` as well which maybe affecting this? Or I've just made a mistake somewhere ...

**Comment by eouia** [comment]
hmmm... yearlyRepeat could make affects, but not sure. I'll test. I haven't tested it.

**Comment by AndyHazz** [comment]
Just checked and if I comment out my yearlyRepeat config, it all works as expected.

**Comment by eouia** [comment]
I guessed what's wrong.
If yearlyRepeat is set, the targetTime would be automatically changed to next year date, so it could never be "after".

hmmm. not bug, but logical dilemma.maybe [n, -n] would be work but not tested.

**Comment by AndyHazz** [comment]
ah, of course!

Well, I don't really need the hide after function on my yearlyRepeat events anyway, it's the hide before that will be most useful.

I did give [n, -n] a go though just to see, and that appears to suffer from the same dilemma.
