### ISSUE TITLE
Problems updating to 2.0.0

### ISSUE THREAD

**Issue by howest99** [eouia/MMM-CountEvents#4]
Thank you for your efforts!  I am having difficulty with this update.  The first issue was permissions on postinstall.sh.  It was set to "none" so I changed it to user and group execute and got past that.  I then did an npm install in both MMM-CountEvents and MMM-CustomElementTime folders.  (some difficulties with Node version - resolved them)

When I started up Magic Mirror , the MMM-CountEvents returned  "Undefined".  I am making some changes to the config to match the minimum config shown in the readme file, and now I don't get anything to work.  

I am not sure what to try next.

**Comment by eouia** [comment]
Can you show me the config and the screenshot?
I'll add the command and instruction for permission.

**Comment by howest99** [comment]
I started over this morning checking node version first, changing the permission on postinstall.sh, and copying the config directly from the readme file, and was able to get it to work!
